### PR TITLE
random walker with fading trail

### PR DESCRIPTION
**Pull request by lithium-anode**

### CODE REVIEW

**Comment by lithium-anode** [comment]
Hello, @atharvakinage, I have opened a PR but it has been very long since I submitted it. Can you please review it?

**Comment by atharvakinage** [comment]
this is not solving the issue, i want the trail to completely fade over time

**Comment by lithium-anode** [comment]
Sorry about that. I will start improving it. Can you please assign me the issue again?

**Comment by atharvakinage** [comment]
yess allright

**Comment by lithium-anode** [comment]
I have pushed the new commit

**Comment by lithium-anode** [comment]
Hello, @atharvakinage, I pushed a new commit quite long ago. Can you please review the code?

**Comment by atharvakinage** [comment]
heyy am really sorry was in some work ill review it rn

**Comment by atharvakinage** [comment]
it seems nice but can you draw more pixels then make it fade and make the walker a little slow, if ur ready to work on it i can reassign it to you, let me know

**Comment by lithium-anode** [comment]
yes, i'll work on it. please reassign it. thank you

**Comment by atharvakinage** [comment]
yess done

**Comment by lithium-anode** [comment]
@atharvakinage , i hope this worked...
please let me know if i have to make any changes

**Comment by atharvakinage** [comment]
ok nice, may i know where you at tho just wanna meet once

**Comment by lithium-anode** [comment]
sem hall 2

**Comment by atharvakinage** [comment]
ohh allright gimme a while

**Comment by atharvakinage** [comment]
oh bro am here can you tell which row or like stand up or something

**Comment by lithium-anode** [comment]
2nd row

**Comment by atharvakinage** [comment]
!bounty 75

**Pull request closed without merging**
